# Generated by Django 2.0.2 on 2019-07-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190705_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='archive',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
