# Generated by Django 2.0.2 on 2019-07-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190718_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='archive',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='page',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='intereses', to='Usuarios.Interests'),
        ),
    ]
