# Generated by Django 2.0.2 on 2019-06-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='datebirth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fecha De Nacimiento'),
        ),
    ]
