# Generated by Django 2.0.2 on 2019-07-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_administrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='user',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
