# Generated by Django 2.0.2 on 2019-06-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20190621_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Indefinido', 'Indefinido')], max_length=30, null=True, verbose_name='Genero'),
        ),
    ]
