# Generated by Django 2.0.2 on 2019-06-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_auto_20190623_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='datebirth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha De Nacimiento'),
        ),
    ]
