# Generated by Django 2.0.2 on 2019-07-03 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_egresadoconsulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='genre',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='egresado',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='egresado',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='validate',
            field=models.CharField(choices=[('validado', 'Validado'), ('Espera', 'Espera'), ('Rechazado', 'Rechazado')], default='Espera', max_length=30, verbose_name='Validación'),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='interests',
            field=models.ManyToManyField(blank=True, to='Usuarios.Interests'),
        ),
    ]
