# Generated by Django 2.0.2 on 2019-07-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_auto_20190703_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
