# Generated by Django 2.0.2 on 2019-07-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_auto_20190705_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresado',
            name='program',
            field=models.TextField(blank=True, null=True, verbose_name='programa'),
        ),
    ]
