# Generated by Django 2.0.2 on 2019-07-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_egresado_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresado',
            name='program',
        ),
        migrations.RemoveField(
            model_name='egresado',
            name='validate',
        ),
        migrations.AddField(
            model_name='user',
            name='validate',
            field=models.BooleanField(default=True),
        ),
    ]
