# Generated by Django 2.0.2 on 2019-07-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_egresados', to='Usuarios.Interests'),
        ),
    ]
