# Generated by Django 2.0.2 on 2019-07-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0011_auto_20190711_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresado',
            name='interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_egresados', to='Usuarios.Interests'),
        ),
    ]
