# Generated by Django 2.0.2 on 2019-07-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0012_auto_20190717_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresado',
            name='country',
        ),
        migrations.RemoveField(
            model_name='egresado',
            name='datebirth',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.TextField(blank=True, null=True, verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='profile',
            name='datebirth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha De Nacimiento'),
        ),
    ]
