# Generated by Django 2.0.2 on 2019-07-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0021_auto_20190718_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_account', to='Usuarios.Profile', verbose_name='Cuenta a seguir'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_user', to='Usuarios.Profile', verbose_name='Seguidor'),
        ),
    ]
